#!/usr/bin/env ruby

branch_name=`git symbolic-ref HEAD`.strip
message_file=ARGV[0]

if branch_name =~ /(--|__)(\w+)\z/
  story_number=$2
  message=File.read(message_file).strip

  exit 0 if message.include?("c/#{story_number}")

  if ARGV[1] == 'message'
    message << "\n\n[https://trello.com/c/#{story_number}]"
  else
    message = "\n\n[https://trello.com/c/#{story_number}]\n" + message
  end
  File.open(message_file, 'w') { |f| f.write(message) }
end
